name: Apply Terraform k8s Cluster

on:
  workflow_dispatch 

env:
  K8S_DIR: "./k8s-cluster"
  YC_TOKEN: ${{ secrets.YC_TOKEN }}

jobs:
  terraform:
    name: "Terraform Apply"
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Terraform Setup
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "~1.10.5"
      
      - name: Terraform init&validate (with Backend)
        working-directory: ${{ env.K8S_DIR }}
        run: |
          terraform init -backend-config "access_key=${{ secrets.ACCESS_KEY }}"  \
          -backend-config="secret_key=${{ secrets.SECRET_KEY }}"
          terraform validate
      
      # - name: Terraform plan
      #   working-directory: ${{ env.K8S_DIR }}
      #   run: |
      #     terraform plan
      
      - name: Terraform apply
        working-directory: ${{ env.K8S_DIR }}
        run: |
          terraform apply -auto-approve
      

      